version: "3"

services:
  mc:
    #user: "${UID_GID}"
    image: itzg/minecraft-server
    ports:
      - ${MC_MAIN_PORT}:25565
      - ${MC_RCON_PORT}:25575
    environment:
      EULA: "TRUE"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "${RCON_SECRET}"
    tty: true
    stdin_open: true
    volumes:
      - ./server-data:/data
  admin:
    image: hcsama/mcadmin
    ports:
      - 8280:80
    environment:
      MCSERVER_ADDR: "mc"
      MCSERVER_SECR: "${RCON_SECRET}"
    links:
      - mc:mc
