#!/bin/bash

source ./util/check_dc_file.sh
source ./util/load_local_config.sh

# Platform agnostic open
function aopen() {
  case $(uname -s) in
        *[Dd]arwin* ) open "$@";;
        *) xdg-open "$@";;
  esac
}

export UID_GID="$(id -u):$(id -g)"

./configure
load_local_config

echo -e "Start minecraft server with user \033[0;32m$UID_GID\033[0m and port $MC_MAIN_PORT"

docker compose up -d
echo "open http://localhost:8280 for admin"
